///////////////////////////////////////////////////////////
//  NhaXuatBan.cs
//  Implementation of the Class NhaXuatBan
//  Generated by Enterprise Architect
//  Created on:      21-Oct-2019 2:05:06 PM
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class NhaXuatBan {

	private String MaNXB;
	private int NamthanhLAP;
	private String TenNXB;

	public NhaXuatBan(){

	}

	~NhaXuatBan(){

	}

	/// 
	/// <param name="maNXB"></param>
	/// <param name="tenNXB"></param>
	/// <param name="namThanhLap"></param>
	public NhaXuatBan(String maNXB, String tenNXB, int namThanhLap){

	}

	public String getMaNhaXuatBan(){

		return "";
	}

	public String getThongTin(){

		return "";
	}

	/// 
	/// <param name="stMaNhaXuatBanMoi"></param>
	public void setMaNhaXuatBan(String stMaNhaXuatBanMoi){

	}

}//end NhaXuatBan